/**
 * Seed a large dataset and benchmark the core "stock shortage" lookup.
 *
 * Run: npm run db:seedbench   (uses web/.env.local DATABASE_URL)
 * Idempotent: skips seeding if the parts table is already populated.
 * Not for production data.
 */
import { config } from "dotenv";

config({ path: ".env.local" });

import { eq, inArray, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";

import * as schema from "../src/lib/db/schema";
import { locations, parts, stockItems } from "../src/lib/db/schema";

const PART_COUNT = 50_000;
const LOCATION_COUNT = 10;
const BOM_SIZE = 200; // a fairly large board's BOM
const BATCH = 2_000;
const RUNS = 10;

const mpnFor = (i: number) => `MPN-${i.toString().padStart(6, "0")}`;

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

async function countParts(db: ReturnType<typeof drizzle>): Promise<number> {
  const rows = await db.select({ c: sql<number>`count(*)::int` }).from(parts);
  return rows[0].c;
}

async function seed(db: ReturnType<typeof drizzle>) {
  console.log("Truncating tables...");
  await db.execute(
    sql`TRUNCATE stock_items, inventory_txns, build_consumptions, builds, bom_lines, boards, parts, locations RESTART IDENTITY CASCADE`,
  );

  console.log(`Seeding ${LOCATION_COUNT} locations...`);
  await db.insert(locations).values(
    Array.from({ length: LOCATION_COUNT }, (_, i) => ({
      name: `BIN-${i + 1}`,
      description: `Storage bin ${i + 1}`,
    })),
  );
  const locIds = (await db.select({ id: locations.id }).from(locations)).map((r) => r.id);

  console.log(`Seeding ${PART_COUNT.toLocaleString()} parts...`);
  const tParts = performance.now();
  const partValues = Array.from({ length: PART_COUNT }, (_, i) => ({
    mpn: mpnFor(i),
    manufacturer: `Mfr ${i % 200}`,
    description: `Generic component ${i}`,
  }));
  for (const c of chunk(partValues, BATCH)) await db.insert(parts).values(c);
  console.log(`  parts inserted in ${(performance.now() - tParts).toFixed(0)}ms`);

  const partIds = (await db.select({ id: parts.id }).from(parts)).map((r) => r.id);

  console.log(`Seeding ${PART_COUNT.toLocaleString()} stock rows...`);
  const tStock = performance.now();
  const stockValues = partIds.map((pid, i) => ({
    partId: pid,
    locationId: locIds[i % locIds.length],
    quantity: Math.floor(Math.random() * 500),
  }));
  for (const c of chunk(stockValues, BATCH)) await db.insert(stockItems).values(c);
  console.log(`  stock inserted in ${(performance.now() - tStock).toFixed(0)}ms`);
}

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL not set (web/.env.local)");
  const client = postgres(url, { prepare: false });
  const db = drizzle(client, { schema });

  if ((await countParts(db)) >= PART_COUNT) {
    console.log(`Parts already seeded — skipping seed.`);
  } else {
    await seed(db);
  }

  // Random BOM of MPNs that exist in the dataset.
  const bom = Array.from({ length: BOM_SIZE }, () => mpnFor(Math.floor(Math.random() * PART_COUNT)));

  // Core shortage lookup: summed on-hand quantity per BOM part (query builder -> inArray).
  const shortageQuery = () =>
    db
      .select({
        mpn: parts.mpn,
        available: sql<number>`COALESCE(SUM(${stockItems.quantity}), 0)`,
      })
      .from(parts)
      .leftJoin(stockItems, eq(stockItems.partId, parts.id))
      .where(inArray(parts.mpn, bom))
      .groupBy(parts.mpn);

  await shortageQuery(); // warm up
  const times: number[] = [];
  for (let i = 0; i < RUNS; i++) {
    const s = performance.now();
    await shortageQuery();
    times.push(performance.now() - s);
  }
  times.sort((a, b) => a - b);
  const avg = times.reduce((a, b) => a + b, 0) / RUNS;

  const single = mpnFor(Math.floor(PART_COUNT / 2));
  const tSingle = performance.now();
  await db.select({ id: parts.id, mpn: parts.mpn }).from(parts).where(eq(parts.mpn, single));
  const singleMs = performance.now() - tSingle;

  // Server-side execution time only (excludes the client<->DB network round-trip).
  const inList = bom.map((m) => `'${m}'`).join(","); // MPNs are generated by us, no injection risk
  const plan = (await db.execute(
    sql.raw(
      `EXPLAIN (ANALYZE, FORMAT JSON) SELECT p.mpn, COALESCE(SUM(s.quantity),0) AS available ` +
        `FROM parts p LEFT JOIN stock_items s ON s.part_id = p.id ` +
        `WHERE p.mpn IN (${inList}) GROUP BY p.mpn`,
    ),
  )) as unknown as Array<{
    "QUERY PLAN": Array<{ "Execution Time": number; "Planning Time": number }>;
  }>;
  const planRoot = plan[0]["QUERY PLAN"][0];

  const partCount = await countParts(db);
  const stockCount = (await db.select({ c: sql<number>`count(*)::int` }).from(stockItems))[0].c;

  console.log(`\nDataset: ${partCount.toLocaleString()} parts, ${stockCount.toLocaleString()} stock rows.`);
  console.log(`Shortage lookup for a ${BOM_SIZE}-line BOM (summed availability):`);
  console.log(
    `  min ${times[0].toFixed(1)}ms | median ${times[Math.floor(RUNS / 2)].toFixed(1)}ms | avg ${avg.toFixed(1)}ms (${RUNS} runs)`,
  );
  console.log(`  single MPN lookup: ${singleMs.toFixed(1)}ms`);
  console.log(
    `Server-side only (EXPLAIN ANALYZE): planning ${planRoot["Planning Time"].toFixed(2)}ms + execution ${planRoot["Execution Time"].toFixed(2)}ms`,
  );
  console.log("  (the gap vs the timings above is local PC <-> Supabase network round-trip)");

  await client.end();
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
